apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    eventstreams.ibm.com/use-connector-resources: 'true'
  name: my-connect-cluster
  namespace: cp4i
spec:
  authentication:
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: kafka
    type: tls
  bootstrapServers: 'development-es-kafka-bootstrap.integration.svc:9093'
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
    config.storage.replication.factor: 3
    config.storage.topic: connect-cluster-configs
    group.id: connect-cluster
    offset.storage.replication.factor: 3
    offset.storage.topic: connect-cluster-offsets
    status.storage.replication.factor: 3
    status.storage.topic: connect-cluster-status
  image: 'bashayralabdullah/cdc:v3'
  replicas: 1
  template:
    buildConfig:
      pullSecret: ibm-entitlement-key
    pod:
      imagePullSecrets:
        - name: my-registry-credentials
      metadata:
        annotations:
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productChargedContainers: my-connect-cluster-connect
          productCloudpakRatio: '2:1'
          productID: 2a79e49111f44ec3acd89608e56138f5
          productMetric: VIRTUAL_PROCESSOR_CORE
          productName: IBM Event Streams for Non Production
          productVersion: 11.2.2
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: development-es-cluster-ca-cert